server:
  port: 8085
  servlet:
    context-path: /demo

#mybatis:
#  typeAliasesPackage: com.yshyerp.crc.entity
#  mapperLocations: classpath:mapping/*.xml

mybatis-plus:
  type-aliases-package: com.yshyerp.crc.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.1.252;databaseName=invdbf
    username: sa
    password: 1qaz@wsx

#logging:
#  pattern:
#    console: "[%thread] %-5level %logger{36} - %msg%n"
#  level:
#    com.smartflow.sprinbootmybatis.mappper: debug

#分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: sqlserver
  params: count=countsql
  pageSizeZero: true
